- name: create a disk
  gcp_compute_disk:
         name: 'disk-instance'
         size_gb: 10
         source_image: 'projects/ubuntu-os-cloud/global/images/ubuntu-1804-bionic-v20190514'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
  register: disk
- name: create a network
  gcp_compute_network:
         name: default
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
  register: network
- name: create a address
  gcp_compute_address:
         name: 'address-instance'
         region: "{{ region }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
  register: address
- name: create a instance
  gcp_compute_instance:
         state: present
         name: vm-from-ansible
         machine_type: g1-small
         disks:
           - auto_delete: true
             boot: true
             source: "{{ disk }}"
         metadata:
             ssh-keys: "{{ rsa_pub_key }}"
         tags:
           items: http-server
         network_interfaces:
             - network: "{{ network }}"
               access_configs:
                 - name: 'External NAT'
                   nat_ip: "{{ address }}"
                   type: 'ONE_TO_ONE_NAT'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
  register: instance
- name: Wait for SSH to come up on instance
  wait_for: host={{ address.address }} port=22 delay=10 timeout=180
- name: Add host to groupname
  add_host: hostname={{ address.address }} groupname=new_instances
